import _ from 'lodash/object'
import * as LoginAction from "./LoginAction";
import * as CustomerAction from "./CustomerAction";
import * as HistoryAction from "./HistoryAction";
import * as RecycleAction from "./RecycleAction";
import * as CommunityAction from "./CommunityAction";

// reducer type.
export const LOGIN_QR_CODE = "LOGIN_QR_CODE"

export const CUSTOMER_MENU_OPEN_KEY = "CUSTOMER_MENU_OPEN_KEY"
export const CUSTOMER_MENU_SELECT_KEY = "CUSTOMER_MENU_SELECT_KEY"

export const CUSTOMER_RECHARGE = "CUSTOMER_RECHARGE"
export const CUSTOMER_SEARCH = "CUSTOMER_SEARCH"
export const CUSTOMER_TEAMS = "CUSTOMER_TEAMS"
export const CUSTOMER_FOLDERS = "CUSTOMER_FOLDERS"
export const CUSTOMER_ACCOUNT = "CUSTOMER_ACCOUNT"
export const CUSTOMER_ACCOUNT_MESSAGE = "CUSTOMER_ACCOUNT_MESSAGE"
export const CUSTOMER_UPDATE_ACCOUNT = "CUSTOMER_UPDATE_ACCOUNT"
export const CUSTOMER_WEBLINKS = "CUSTOMER_WEBLINKS"
export const CUSTOMER_SHARE_FOLDERS = "CUSTOMER_SHARE_FOLDERS"
export const CUSTOMER_OPEN_ACTIVE_FOLDERS = "CUSTOMER_OPEN_ACTIVE_FOLDERS"
export const CUSTOMER_SHARE_FOLDER = "CUSTOMER_SHARE_FOLDER"
export const CUSTOMER_SHARE_COLL = "CUSTOMER_SHARE_COLL"
export const CUSTOMER_SHARE_INFO = "CUSTOMER_SHARE_INFO"
export const CUSTOMER_SHARE_FOLDER_CLEAR = "CUSTOMER_SHARE_FOLDER_CLEAR"
export const CUSTOMER_SHARE_ALL_PERSONNEL = "CUSTOMER_SHARE_ALL_PERSONNEL"
export const CUSTOMER_WORKSPACES = "CUSTOMER_WORKSPACES"
export const CUSTOMER_WORKSPACE = "CUSTOMER_WORKSPACE"
export const CUSTOMER_WORKSPACE_SWITCH = "CUSTOMER_WORKSPACE_SWITCH"
export const CUSTOMER_INVITE = "CUSTOMER_INVITE"
export const CUSTOMER_ORDER = "CUSTOMER_ORDER"
export const CUSTOMER_ORDER_CLEAR = "CUSTOMER_ORDER_CLEAR"
export const CUSTOMER_ORDER_STATUS = "CUSTOMER_ORDER_STATUS"
export const CUSTOMER_ORDER_TRANSACTIONS = "CUSTOMER_ORDER_TRANSACTIONS"
export const CUSTOMER_STATION_CATEGORY = "CUSTOMER_STATION_CATEGORY"
export const CUSTOMER_STATION = "CUSTOMER_STATION"
export const CUSTOMER_STATION_APPEND = "CUSTOMER_STATION_APPEND"
export const CUSTOMER_STATION_META = "CUSTOMER_STATION_META"
export const CUSTOMER_STATION_DETAIL = "CUSTOMER_STATION_DETAIL"
export const CUSTOMER_STATION_AUDIT = "CUSTOMER_STATION_AUDIT"
export const CUSTOMER_COMMUNITY_CATEGORY = "CUSTOMER_COMMUNITY_CATEGORY"
export const CUSTOMER_COMMUNITY = "CUSTOMER_COMMUNITY"
export const CUSTOMER_COMMUNITY_DETAIL = "CUSTOMER_COMMUNITY_DETAIL"
export const CUSTOMER_COMMUNITY_META = "CUSTOMER_COMMUNITY_META"
export const CUSTOMER_COMMUNITY_SELF = "CUSTOMER_COMMUNITY_SELF"
export const CUSTOMER_COMMUNITY_AUDIT = "CUSTOMER_COMMUNITY_AUDIT"
export const CUSTOMER_COMMUNITY_AUDIT_STATUS = "CUSTOMER_COMMUNITY_AUDIT_STATUS"
export const CUSTOMER_ARTICLE_CATEGORY = "CUSTOMER_ARTICLE_CATEGORY"
export const CUSTOMER_ARTICLE = "CUSTOMER_ARTICLE"
export const CUSTOMER_ARTICLE_META = "CUSTOMER_ARTICLE_META"
export const CUSTOMER_ARTICLE_APPEND = "CUSTOMER_ARTICLE_APPEND"
export const CUSTOMER_ARTICLE_COLLECTION = "CUSTOMER_ARTICLE_COLLECTION"
export const CUSTOMER_ARTICLE_SUBMIT = "CUSTOMER_ARTICLE_SUBMIT"
export const CUSTOMER_ARTICLE_AUDIT = "CUSTOMER_ARTICLE_AUDIT"
export const CUSTOMER_ARTICLE_MENU = "CUSTOMER_ARTICLE_MENU"
export const CUSTOMER_ARTICLE_UPDATE = "CUSTOMER_ARTICLE_UPDATE"
export const CUSTOMER_ARTICLE_HOT = "CUSTOMER_ARTICLE_HOT"

export const HISTORY_RECENT_WEBLINK = "HISTORY_RECENT_WEBLINK"

export const RECYCLE_WEBLINK = "RECYCLE_WEBLINK"

// 循环和文件一样，不然会报错
const actions = _.assign(
    CustomerAction,
    HistoryAction,
    LoginAction,
    RecycleAction,
    CommunityAction
);

export default actions;